import json
import os

db_path = r'c:\Users\NexSecure\Desktop\majisa restorent website\data\db.json'

with open(db_path, 'r', encoding='utf-8') as f:
    db = json.load(f)

menu = [
    # --- PANEER ---
    { "id": "paneer-1", "name": "Majisa Special", "hindiName": "माजीसा स्पेशल", "description": "Majisa chef special royal paneer gravy dish.", "price": 270, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "paneer-2", "name": "Kadai Paneer", "hindiName": "कड़ाई पनीर", "description": "Cottage cheese cooked with bell peppers and fresh ground kadai spices.", "price": 190, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-3", "name": "Paneer Butter Masala", "hindiName": "पनीर बटर मसाला", "description": "Paneer cubes simmered in a rich tomato, butter, and cream gravy.", "price": 220, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-4", "name": "Paneer Tikka Masala", "hindiName": "पनीर टिक्का मसाला", "description": "Char-grilled paneer pieces cooked in a spicy onion tomato masala.", "price": 210, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-5", "name": "Paneer Chana", "hindiName": "पनीर चना", "description": "Combination of tender chickpeas and soft paneer in spiced curry.", "price": 160, "category": "paneer", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-6", "name": "Paneer Bhurji Dry", "hindiName": "पनीर भुर्जी सुखी", "description": "Scrambled cottage cheese tossed with onions, tomatoes and green chillies.", "price": 230, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-7", "name": "Paneer Bhurji Gravy", "hindiName": "पनीर भुर्जी ग्रेवी", "description": "Scrambled paneer simmered in a spiced tomato-onion gravy.", "price": 210, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-8", "name": "Shahi Paneer", "hindiName": "शाही पनीर", "description": "Royal dish of paneer cooked in a mild cashew and saffron gravy.", "price": 180, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-9", "name": "Mutter Paneer", "hindiName": "मटर पनीर", "description": "Classic North Indian combination of green peas and paneer.", "price": 170, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-10", "name": "Handi Paneer", "hindiName": "हांडी पनीर", "description": "Paneer cooked in a traditional earthenware handi with ground spices.", "price": 190, "category": "paneer", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-11", "name": "Tawa Paneer", "hindiName": "तवा पनीर", "description": "Paneer cooked on a flat tawa with bell peppers and roasted spices.", "price": 200, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-12", "name": "Paneer Lawabdar", "hindiName": "पनीर लवाबदार", "description": "Paneer cooked in a luscious tomato, cashew and spice mix gravy.", "price": 240, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-13", "name": "Paneer Mastani", "hindiName": "पनीर मस्तानी", "description": "A rich and delicious rich paneer creation with flavorful spices.", "price": 310, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "paneer-14", "name": "Paneer Makmal", "hindiName": "पनीर मकमल", "description": "Silky smooth velvety creamy paneer gravy.", "price": 270, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-15", "name": "Raja Rani Sp. Paneer", "hindiName": "राजा रानी एसपी. पनीर", "description": "Royal style dual gravy paneer dish.", "price": 290, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "paneer-16", "name": "Paneer Rajwadi", "hindiName": "पनीर राजवाड़ी", "description": "Rajasthani royal style aromatic paneer curry.", "price": 230, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-17", "name": "Paneer Chatpata", "hindiName": "पनीर चटपटा", "description": "Tangy and spicy paneer dish tossed in special chaska masala.", "price": 190, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-18", "name": "Paneer Jwalamukhi", "hindiName": "पनीर ज्वालामूखी", "description": "Extremely fiery and spicy paneer sizzler gravy.", "price": 280, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-19", "name": "Paneer Maharaja", "hindiName": "पनीर महाराजा", "description": "Richly spiced paneer dish fit for royalty.", "price": 260, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-20", "name": "Paneer Laska", "hindiName": "पनीर लस्का", "description": "Special recipe paneer in flavorful creamy sauce.", "price": 240, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-21", "name": "Paneer Patiyala", "hindiName": "पनीर पटियाला", "description": "Paneer stuffed in papad roll and served in rich gravy.", "price": 280, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-22", "name": "Paneer Rashmalai (Sweet)", "hindiName": "पनीर रशमलाई ( मीठा )", "description": "Sweet dessert paneer preparation in cardamom milk base.", "price": 190, "category": "paneer", "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-23", "name": "Paneer Tiranga Special", "hindiName": "पनीर तिरंगा स्पेशल", "description": "Three layer paneer gravy with distinctive flavors.", "price": 290, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "paneer-24", "name": "Paneer Dil Kush", "hindiName": "पनीर दिल कुश", "description": "Hearty paneer dish made with aromatic herbs.", "price": 270, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-25", "name": "Paneer Long Latta", "hindiName": "पनीर लोंग लता", "description": "Cloves infused aromatic paneer curry.", "price": 280, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-26", "name": "Paneer Kasturi", "hindiName": "पनीर कस्तूरी", "description": "Paneer cooked with aromatic fenugreek (kasuri methi).", "price": 290, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-27", "name": "Paneer Lashuniya", "hindiName": "पनीर लशुनिया", "description": "Garlic infused rich and spicy paneer gravy.", "price": 250, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-28", "name": "Paneer Achaari", "hindiName": "पनीर अचारी", "description": "Tangy pickle-flavored paneer gravy with mustard and fennel.", "price": 290, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-29", "name": "Paneer Peri Peri Special", "hindiName": "पनीर पेरी पेरी स्पेशल", "description": "Modern fusion paneer tossed in zesty peri-peri spices.", "price": 260, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-30", "name": "Paneer Pasanda", "hindiName": "पनीर पसंदा", "description": "Stuffed paneer triangles cooked in a rich onion-cashew gravy.", "price": 270, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-31", "name": "Paneer Shahi Korma (Sweet)", "hindiName": "पनीर शाही कोरमा ( मीठा )", "description": "Mild, rich sweet paneer korma made with cashew paste and dry fruits.", "price": 240, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-32", "name": "Paneer Kolahapuri", "hindiName": "पनीर कोलाहपुरी", "description": "Fiery Maharastrian style paneer curry with ground coconut and red chillies.", "price": 190, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-33", "name": "Paneer Angara", "hindiName": "पनीर अंगारा", "description": "Smokey charcoal-flavored paneer gravy cooked with whole spices.", "price": 260, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-34", "name": "Paneer Toofani", "hindiName": "पनीर तूफानी", "description": "Spicy storm of paneer cubes and crunchy veggies in rich gravy.", "price": 230, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-35", "name": "Paneer Tawa Masala", "hindiName": "पनीर तवा मसाला", "description": "Dry and thick paneer gravy cooked on live iron griddle.", "price": 230, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-36", "name": "Paneer Afgani", "hindiName": "पनीर अफगानी", "description": "Creamy paneer preparation with white pepper and rich Afghan spices.", "price": 351, "category": "paneer", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "paneer-37", "name": "Paneer Kranti", "hindiName": "पनीर क्रांति", "description": "Special chef creation paneer curry.", "price": 280, "category": "paneer", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "paneer-38", "name": "Punjabi Matka Paneer", "hindiName": "पंजाबी मटका पनीर", "description": "Traditional Punjabi style paneer cooked and served in clay matka.", "price": 299, "category": "paneer", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- HARI SABJI ---
    { "id": "hari-1", "name": "Methi Mutter", "hindiName": "मेथी मटर", "description": "Fresh fenugreek leaves cooked with green peas.", "price": 120, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "hari-2", "name": "Methi Malai", "hindiName": "मेथी मलाई", "description": "Creamy fenugreek preparation cooked in rich white gravy.", "price": 130, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "hari-3", "name": "Methi Tamator", "hindiName": "मेथी टमाटर", "description": "Tangy fenugreek leaves tossed with fresh tomatoes.", "price": 120, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "hari-4", "name": "Bhindi Masala", "hindiName": "भिण्डी मसाला", "description": "Tender okra pan fried with onion tomato masala.", "price": 130, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "hari-5", "name": "Bhindi Fry", "hindiName": "भिण्डी फ्राई", "description": "Crispy fried okra seasoned with dry spices.", "price": 130, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "hari-6", "name": "Hara Piyaz", "hindiName": "हरा प्याज", "description": "Sautéed fresh spring green onions.", "price": 120, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "hari-7", "name": "Hara Piyaz Masala", "hindiName": "हरा प्याज मसाला", "description": "Spring onions cooked with spicy highway masala.", "price": 130, "category": "hari_sabji", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },

    # --- RAITA + CURD ---
    { "id": "raita-1", "name": "Raita Masala Fry", "hindiName": "रायता मसाला फ्राई", "description": "Whisked yogurt seasoned with roasted cumin and fried spices.", "price": 100, "category": "raita", "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "raita-2", "name": "Raita M. Jadka", "hindiName": "रायता एम. झटका", "description": "Special spicy garlic tadka raita.", "price": 130, "category": "raita", "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "raita-3", "name": "Bundi Raita", "hindiName": "बुन्दी रायता", "description": "Traditional yogurt raita with crispy chickpea boondi.", "price": 110, "category": "raita", "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "raita-4", "name": "Veg. Raita", "hindiName": "वैज. रायता", "description": "Freshly chopped cucumbers, tomatoes and onions in spiced curd.", "price": 110, "category": "raita", "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "raita-5", "name": "Plain Dahi", "hindiName": "प्लेन दही", "description": "Fresh thick homemade curd.", "price": 40, "category": "raita", "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "raita-6", "name": "Butter Milk", "hindiName": "छाछ", "description": "Traditional chilled Marwari spiced buttermilk with roasted jeera.", "price": 20, "category": "raita", "image": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },

    # --- RICE & BIRYANI ---
    { "id": "rice-1", "name": "Plain Rice", "hindiName": "प्लेन राईस", "description": "Steamed basmati rice.", "price": 100, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-2", "name": "Jeera Rice", "hindiName": "जीरा राईस", "description": "Basmati rice tempered with ghee and cumin seeds.", "price": 110, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-3", "name": "Fried Rice", "hindiName": "फ्राईड राईस", "description": "Indo-Chinese style vegetable fried rice.", "price": 130, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-4", "name": "Masala Rice", "hindiName": "मसाला राईस", "description": "Spiced basmati rice cooked with Indian aromatic spices.", "price": 130, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-5", "name": "Veg. Pulav", "hindiName": "वैज पुलाव", "description": "Fragrant basmati rice tossed with fresh garden vegetables.", "price": 150, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-6", "name": "Mutter Pulav", "hindiName": "मटर पुलाव", "description": "Basmati rice cooked with sweet tender green peas.", "price": 170, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-7", "name": "Veg. Biriyani", "hindiName": "वैज. बिरयानी", "description": "Aromatic dum cooked vegetable biryani served with spices.", "price": 180, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-8", "name": "Paneer Pulav", "hindiName": "पनीर पुलाव", "description": "Rice cooked with fried paneer cubes and mild spices.", "price": 180, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-9", "name": "Kaju Pulav", "hindiName": "काजु पुलाव", "description": "Royal rice dish tossed with golden fried cashews and ghee.", "price": 190, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-10", "name": "Cheese Pulav", "hindiName": "चीज पुलाव", "description": "Rice pulao topped with melted processed cheese.", "price": 180, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-11", "name": "Handi Biriyani", "hindiName": "हाण्डी बिरयानी", "description": "Clay handi slow cooked dum biryani with herbs.", "price": 180, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-12", "name": "Hyderabadi Biriyani", "hindiName": "हैदराबादी बिरयानी", "description": "Spicy Hyderabadi style layered vegetable biryani.", "price": 180, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-13", "name": "Paneer Biriyani", "hindiName": "पनीर बिरयानी", "description": "Layered aromatic rice with marinated paneer tikka.", "price": 230, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-14", "name": "Cheese Biriyani", "hindiName": "चीज बिरयानी", "description": "Cheesy spicy layered biryani.", "price": 290, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-15", "name": "Paneer Gravy Biriyani", "hindiName": "पनीर ग्रेवी बिरयानी", "description": "Biryani served with rich paneer gravy mix.", "price": 250, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "rice-16", "name": "Majisa Special Biriyani", "hindiName": "माजीसा स्पेशल बिरयानी", "description": "Chef's signature biryani loaded with dry fruits, paneer and spices.", "price": 290, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "rice-17", "name": "Tiranga Biriyani", "hindiName": "तिरंगा बिरयानी", "description": "Tri-colored rice presentation with distinct spicy and herbal layers.", "price": 290, "category": "rice", "image": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- ROTI & BREADS ---
    { "id": "roti-1", "name": "Plain Roti", "hindiName": "तवा रोटी", "description": "Fresh whole wheat tawa roti.", "price": 10, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-2", "name": "Butter Roti", "hindiName": "बटर रोटी", "description": "Tawa roti smeared with fresh Amul butter.", "price": 15, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-3", "name": "Khoba Roti", "hindiName": "खोबा रोटी", "description": "Authentic thick indented Rajasthani bread cooked with ghee.", "price": 60, "category": "breads", "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "roti-4", "name": "Jalore Tukkad", "hindiName": "जालोरी टुकड", "description": "Traditional crispy wheat tukkad bread from Jalore region.", "price": 50, "category": "breads", "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-5", "name": "Bajari Sogra", "hindiName": "बाजरी सोगरा", "description": "Thick pearl millet flatbread slow-cooked on clay tawa.", "price": 30, "category": "breads", "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-6", "name": "Tandoori Roti", "hindiName": "तन्दूरी रोटी", "description": "Whole wheat bread baked in clay tandoor.", "price": 18, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-7", "name": "Tandoori Butter", "hindiName": "तन्दूरी बटर", "description": "Clay tandoor baked bread brushed with rich butter.", "price": 20, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-8", "name": "Plain Naan", "hindiName": "प्लेन नॉन", "description": "Soft refined flour bread baked in tandoor.", "price": 50, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-9", "name": "Butter Naan", "hindiName": "बटर नॉन", "description": "Soft tandoori naan coated with melted butter.", "price": 60, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-10", "name": "Cheese Naan", "hindiName": "चीज नॉन", "description": "Naan bread stuffed with melted cheese.", "price": 80, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-11", "name": "Garlic Naan", "hindiName": "गारलीक नॉन", "description": "Tandoori naan topped with crushed garlic and coriander.", "price": 80, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-12", "name": "Cheese Garlic Naan", "hindiName": "चीज गारलीक नॉन", "description": "Stuffed cheese naan infused with aromatic roasted garlic.", "price": 100, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "roti-13", "name": "Jatka Naan", "hindiName": "झटका नॉन", "description": "Spicy signature naan with special highway chilli seasoning.", "price": 110, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": True },
    { "id": "roti-14", "name": "Butter Kulcha", "hindiName": "बटर कुल्छा", "description": "Fluffy leavened flatbread brushed with butter.", "price": 80, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "roti-15", "name": "Laccha Paratha", "hindiName": "लच्छा पराठा", "description": "Multi-layered flaky whole wheat paratha baked in tandoor.", "price": 80, "category": "breads", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },

    # --- FIX THALI ---
    { "id": "thali-1", "name": "(Fix) Thali", "hindiName": "(फिक्स) थाली", "description": "Includes Sev Tamatar, Dal, Rice, and 5 Plain Rotis.", "price": 130, "category": "thali", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "thali-2", "name": "Rajasthani (Fix Thali)", "hindiName": "राजस्थानी (फिक्स थाली)", "description": "Includes Kadhi, Raita, Mix Veg, 2 Ghee Sogra, Buttermilk, and Rice.", "price": 180, "category": "thali", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "thali-3", "name": "Punjabi Special (Fix Thali)", "hindiName": "पंजाबी स्पेशल (फिक्स थाली)", "description": "Includes Paneer Sabji, Veg Sabji, Dal, Jeera Rice, 5 Ghee Rotis, Papad, and Buttermilk.", "price": 190, "category": "thali", "image": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- SALAD & PAPAD ---
    { "id": "salad-1", "name": "Green Salad", "hindiName": "ग्रीन सलाद", "description": "Freshly sliced cucumbers, tomatoes, onions, and lemon.", "price": 50, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-2", "name": "Plain Piyaj", "hindiName": "प्लेन प्याज", "description": "Sliced raw red onions with green chilli.", "price": 20, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-3", "name": "Plain Papad", "hindiName": "प्लेन पापड़", "description": "Roasted or fried urad papad.", "price": 20, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-4", "name": "Masala Papad", "hindiName": "मसाला पापड़", "description": "Crispy papad topped with finely chopped onion, tomato and spices.", "price": 50, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-5", "name": "Plain Khichiya", "hindiName": "प्लेन खिचिया", "description": "Traditional rice crisp flat papad.", "price": 30, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-6", "name": "Masala Khichiya", "hindiName": "मसाला खिचिया", "description": "Rice papad topped with spicy onion tomato chat masala.", "price": 60, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-7", "name": "Plain Lilka", "hindiName": "प्लेन लिलका", "description": "Plain lilka crispy accompaniment.", "price": 20, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-8", "name": "Masala Lilka", "hindiName": "मसाला लिलका", "description": "Spiced lilka crispy side dish.", "price": 50, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-9", "name": "Masala Namkin", "hindiName": "मसाला नमकीन", "description": "Spiced Rajasthani roasted mixture snacks.", "price": 60, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-10", "name": "Papad Churi", "hindiName": "पापड़ चूरी", "description": "Crushed roasted papad tossed in ghee and Marwari spices.", "price": 60, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "salad-11", "name": "Ghee Mirchi Lilka", "hindiName": "घी मिर्ची लिलका", "description": "Lilka crisp tossed in cow ghee and red chillies.", "price": 30, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-12", "name": "Ghee Mirchi Papad", "hindiName": "घी मिर्ची पापड़", "description": "Crispy papad brushed with pure ghee and Mathania chilli powder.", "price": 30, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "salad-13", "name": "Ghee Mirchi Khichiya", "hindiName": "घी मिर्ची खिचिया", "description": "Rice khichiya dipped in ghee and sprinkled with spicy masala.", "price": 40, "category": "salad", "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },

    # --- RAJASTHANI SPECIAL SABJI ---
    { "id": "raj-1", "name": "Special Haldi (Winter)", "hindiName": "स्पेशल हल्दी ( सर्दी में )", "description": "Winter special fresh raw turmeric sabji slow cooked in pure cow ghee.", "price": 250, "category": "raj_special", "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "raj-2", "name": "Special Kadhi", "hindiName": "स्पेशल कढ़ी", "description": "Traditional sour yogurt and gram flour Rajasthani kadhi tempered with mustard seeds.", "price": 120, "category": "raj_special", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "raj-3", "name": "Lahsun Chatni", "hindiName": "लहसुन चटनी", "description": "Fiery Marwari garlic chutney cooked in ghee.", "price": 110, "category": "raj_special", "image": "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "raj-4", "name": "Besan Gatta", "hindiName": "बेसन गट्टा", "description": "Gram flour dumplings cooked in a spiced yogurt gravy.", "price": 120, "category": "raj_special", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },

    # --- MAJISA SPECIAL CHURMA ---
    { "id": "churma-1", "name": "Desi Gud Sogra Churma", "hindiName": "देसी गुड सोगरा चूरमा ( 2 )", "description": "Traditional crushed pearl millet bread churma mixed with organic jaggery and ghee (2 pcs).", "price": 151, "category": "churma", "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "churma-2", "name": "Jalori Tukad Churma", "hindiName": "जालोरी टुकड चूरमा ( 1 )", "description": "Authentic Jalore style wheat tukad churma soaked in pure ghee.", "price": 151, "category": "churma", "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "churma-3", "name": "Khoba Churma", "hindiName": "खोबा चूरमा ( 1 )", "description": "Rich churma prepared from sweet indented Khoba bread and cardamom syrup.", "price": 151, "category": "churma", "image": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- VEGETABLE SABJI ---
    { "id": "veg-1", "name": "Sev Tamatar", "hindiName": "सेव टमाटर", "description": "Famous spicy tomato gravy topped with crispy gram flour sev noodles.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-2", "name": "Sev Bhaji", "hindiName": "सेव भाजी", "description": "Sev cooked in spicy onion and tomato Dhaba bhaji style.", "price": 150, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-3", "name": "Sev Piyaz Masala", "hindiName": "सेव प्याज मसाला", "description": "Crunchy sev tossed with spicy onions and roasted gravy.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-4", "name": "Sev Lahsuniya", "hindiName": "सेव लहसुनिया", "description": "Garlic loaded fiery sev curry.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-5", "name": "Sev Malai", "hindiName": "सेव मलाई", "description": "Sev cooked in mild creamy white malai gravy.", "price": 120, "category": "mains", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-6", "name": "Mix Veg.", "hindiName": "मिक्स वैज", "description": "Assorted fresh seasonal vegetables cooked in aromatic spices.", "price": 150, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-7", "name": "Veg. Lahsaniya", "hindiName": "वैज लहसुनिया", "description": "Mixed vegetables prepared with rich roasted garlic flavor.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-8", "name": "Veg. Kadai", "hindiName": "वैज कढ़ाई", "description": "Vegetables cooked with crushed kadai spices and capsicum.", "price": 150, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-9", "name": "Veg. Toofani", "hindiName": "वैज तुफानी", "description": "Spicy combination of garden veggies in dark red spicy gravy.", "price": 180, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-10", "name": "Veg. Angara", "hindiName": "वैज अंगारा", "description": "Smokey charcoal infused vegetables curry.", "price": 190, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-11", "name": "Veg. Tava Masala", "hindiName": "वैज तवा मसाला", "description": "Vegetables pan fried on live iron tava with onion tomato spices.", "price": 180, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-12", "name": "Veg. Maharaja", "hindiName": "वैज महाराजा", "description": "Royal vegetable dish cooked with rich cream and spices.", "price": 180, "category": "mains", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "veg-13", "name": "Mutter Tamatar", "hindiName": "मटर टमाटर", "description": "Green peas cooked with tangy tomato gravy.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-14", "name": "Channa Masala", "hindiName": "चना मसाला", "description": "Tender chickpeas simmered in a tangy Punjabi masala.", "price": 110, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-15", "name": "Channa Dry", "hindiName": "चना ड्राई", "description": "Dry sautéed chickpeas with spices and herbs.", "price": 120, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-16", "name": "Piyaz Tamatar", "hindiName": "प्याज टमाटर", "description": "Classic Dhaba style onion tomato sautéed sabji.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-17", "name": "Veg. Kolhapuri", "hindiName": "वैज. कोल्हापुरी", "description": "Spicy Maharashtrian mix vegetable curry.", "price": 150, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-18", "name": "Veg. Jaipuri", "hindiName": "वैज. जयपुरी", "description": "Jaipuri style vegetable curry garnished with roasted papad.", "price": 180, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-19", "name": "Aaloo Piyaj", "hindiName": "आलु प्याज", "description": "Homestyle spiced potato and onion dish.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-20", "name": "Aaloo Tamatar", "hindiName": "आलु टमाटर", "description": "Dhaba style potato curry in tangy tomato broth.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-21", "name": "Veg. Diwani Handi", "hindiName": "वैज. दिवानी हाण्डी", "description": "Vegetables cooked in slow heat handi with creamy spinach and spices.", "price": 190, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "veg-22", "name": "Aaloo Mutter", "hindiName": "आलु मटर", "description": "Comforting dish of potatoes and green peas in tomato onion curry.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-23", "name": "Malai Piyaj", "hindiName": "मलाई प्याज", "description": "Sweet small onions cooked in rich creamy white gravy.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "veg-24", "name": "Malai Mutter", "hindiName": "मलाई मटर", "description": "Green peas cooked in soft rich cashew malai sauce.", "price": 130, "category": "mains", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },

    # --- KAJU ---
    { "id": "kaju-1", "name": "Kaju Curry", "hindiName": "काजु करी", "description": "Whole roasted cashew nuts simmered in a rich tomato onion curry.", "price": 220, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "kaju-2", "name": "Kaju Masala", "hindiName": "काजु मसाला", "description": "Cashew nuts tossed in spicy onion tomato Dhaba masala.", "price": 220, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kaju-3", "name": "Kaju Lahsuniya", "hindiName": "काजु लहसुनिया", "description": "Cashews cooked with roasted garlic infused rich gravy.", "price": 230, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kaju-4", "name": "Kaju Angara", "hindiName": "काजु अंगारा", "description": "Smokey charcoal flavored spicy cashew nut gravy.", "price": 250, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kaju-5", "name": "Kaju Kadai", "hindiName": "काजु कढाई", "description": "Cashews cooked with bell peppers and coarse ground kadai spices.", "price": 220, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "kaju-6", "name": "Kaju Paneer Masala", "hindiName": "काजु पनीर मसाला", "description": "Rich combination of crunchy cashews and soft cottage cheese.", "price": 220, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kaju-7", "name": "Kaju Butter Masala", "hindiName": "काजु बटर मसाला", "description": "Cashew nuts in butter loaded smooth tomato cream gravy.", "price": 220, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kaju-8", "name": "Khoya Sweet Kaju", "hindiName": "खोया स्वीट काजु", "description": "Sweet royal cashew preparation cooked with khoya and dry fruits.", "price": 200, "category": "kaju", "image": "https://images.unsplash.com/photo-1585938338990-d2242b512995?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- CHEESE (SPECIAL) ---
    { "id": "cheese-1", "name": "Cheese Angara", "hindiName": "चीज अंगारा", "description": "Smokey spicy cheese preparation cooked on coal embers.", "price": 220, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "cheese-2", "name": "Cheese Lahsuniya", "hindiName": "चीज लहसुनिया", "description": "Grated cheese cooked in a spicy roasted garlic gravy.", "price": 230, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "cheese-3", "name": "Cheese Anguri", "hindiName": "चीज अंगूरी", "description": "Cheese balls cooked in rich spicy royal gravy.", "price": 230, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "cheese-4", "name": "Cheese Paneer Masala", "hindiName": "चीज पनीर मसाला", "description": "Decadent blend of processed cheese and soft paneer.", "price": 220, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "cheese-5", "name": "Cheese Butter Masala", "hindiName": "चीज बटर मसाला", "description": "Grated cheese simmered in butter and tomato cream gravy.", "price": 230, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "cheese-6", "name": "Cheese Masala", "hindiName": "चीज मसाला", "description": "Spicy onion tomato gravy overloaded with cheese.", "price": 220, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "cheese-7", "name": "Cheese Kaju Masala", "hindiName": "चीज काजु मसाला", "description": "Fried cashew nuts and melted cheese in aromatic gravy.", "price": 240, "category": "cheese", "image": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- KOFTA ---
    { "id": "kofta-1", "name": "Veg. Kofta", "hindiName": "वैज. कोफ्ता", "description": "Deep fried vegetable dumplings in a seasoned tomato onion curry.", "price": 180, "category": "kofta", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kofta-2", "name": "Malai Kofta", "hindiName": "मलाई कोफ्ता", "description": "Soft cottage cheese and potato dumplings in creamy cashew gravy.", "price": 180, "category": "kofta", "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "kofta-3", "name": "Paneer Kofta", "hindiName": "पनीर कोफ्ता", "description": "Stuffed paneer balls served in aromatic gravy.", "price": 190, "category": "kofta", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "kofta-4", "name": "Cheese Kofta", "hindiName": "चीज कोफ्ता", "description": "Cheese stuffed crispy koftas cooked in tomato gravy.", "price": 200, "category": "kofta", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "kofta-5", "name": "Kaju Kofta", "hindiName": "काजु कोफ्ता", "description": "Cashew stuffed rich dumplings in royal gravy.", "price": 220, "category": "kofta", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "kofta-6", "name": "Mili Juli Kofta Curry", "hindiName": "मिली जुली कोफ्ता करी", "description": "Chef special mixed kofta assortment in flavorful sauce.", "price": 281, "category": "kofta", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },

    # --- DAL ---
    { "id": "dal-1", "name": "Dal Fry", "hindiName": "दाल फ्राई", "description": "Yellow lentils tempered with ghee, cumin, garlic and green chillies.", "price": 110, "category": "dal", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "dal-2", "name": "Dal Butter Fry", "hindiName": "दाल बटर फ्राई", "description": "Lentil fry cooked with extra Amul butter.", "price": 130, "category": "dal", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "dal-3", "name": "Dal Tadka", "hindiName": "दाल तड़का", "description": "Yellow dal finished with a double sizzling ghee garlic tadka.", "price": 130, "category": "dal", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True },
    { "id": "dal-4", "name": "Dal Palak", "hindiName": "दाल पालक", "description": "Nutritious combination of yellow dal cooked with fresh spinach.", "price": 130, "category": "dal", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "dal-5", "name": "Dal Chawal Khichidi", "hindiName": "दाल चावल खिचड़ी", "description": "Comfort meal of rice and lentils cooked together with mild spices.", "price": 150, "category": "dal", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "dal-6", "name": "Kadi Chawal Khichdi", "hindiName": "कड़ी चावल खिचड़ी", "description": "Rajasthani kadhi served with spiced rice khichdi.", "price": 150, "category": "dal", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },

    # --- PALAK ---
    { "id": "palak-1", "name": "Palak Lahsuniya", "hindiName": "पालक लहसुनिया", "description": "Fresh spinach puree cooked with fragrant roasted garlic.", "price": 140, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-2", "name": "Kaju Palak", "hindiName": "काजु पालक", "description": "Golden cashews in smooth seasoned spinach gravy.", "price": 200, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-3", "name": "Cheese Palak", "hindiName": "चीज पालक", "description": "Processed cheese blended with spiced spinach puree.", "price": 220, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-4", "name": "Mutter Palak", "hindiName": "मटर पालक", "description": "Green peas cooked in seasoned spinach curry.", "price": 130, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-5", "name": "Palak Tamator", "hindiName": "पालक टमाटर", "description": "Spinach cooked with juicy chopped tomatoes.", "price": 120, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-6", "name": "Aaloo Palak", "hindiName": "आलु पालक", "description": "Diced potatoes tossed in spiced spinach gravy.", "price": 120, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-7", "name": "Plain Palak", "hindiName": "प्लेन पालक", "description": "Simple seasoned spinach curry.", "price": 110, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": False, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-8", "name": "Palak Paneer", "hindiName": "पालक पनीर", "description": "Cottage cheese cubes in smooth seasoned spinach gravy.", "price": 170, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": False, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-9", "name": "Palak Panner Bhurji", "hindiName": "पालक पनीर भुर्जी", "description": "Scrambled paneer tossed with fresh spiced spinach.", "price": 240, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": False },
    { "id": "palak-10", "name": "Special Paneer Hyderabadi", "hindiName": "स्पेशल पनीर हैदराबादी", "description": "Hyderabadi style spicy green herbal paneer gravy.", "price": 240, "category": "palak", "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80", "isSpicy": True, "isPopular": True, "isAvailable": True, "isChefSpecial": True }
]

db['menu'] = menu

with open(db_path, 'w', encoding='utf-8') as f:
    json.dump(db, f, ensure_ascii=False, indent=2)

print(f"Successfully updated menu in db.json with {len(menu)} items!")
